[crawler]
interval_secs = 10
timeout_secs = 120
subject_code = "cs"
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36 Edg/145.0.0.0"

[prompts]
dir = "prompts"

[filter]
relevance_threshold = 70
eval_concurrency = 8

[[topics]]
name = "Concurrent reasoning"
description = "基于形式化方法（如模型检测、定理证明）对并发程序进行正确性分析的相关研究，重点关注系统并发行为的建模、规约与验证。"

[[topics]]
name = "LLM4SE"
description = "面向大型软件系统的智能化构建与优化：研究大语言模型如何辅助代码开发、测试调试、形式化验证，并探索其在系统自动化调优方面的核心方法与关键技术。"

[ai]

[ai.models."deepseek-chat"]
provider = "deepseek"
endpoint = "https://api.deepseek.com/chat/completions"
system_prompt = "You are a helpful assistant"
timeout_secs = 60

[ai.models."deepseek-chat".request]
model = "deepseek-chat"
thinking_type = "disabled"
frequency_penalty = 0.0
max_tokens = 4096
presence_penalty = 0.0
response_format_type = "text"
stream = false
temperature = 1.0
top_p = 1.0
tool_choice = "none"
logprobs = false

[ai.models."deepseek-reasoner"]
provider = "deepseek"
endpoint = "https://api.deepseek.com/chat/completions"
system_prompt = "You are a helpful assistant"
timeout_secs = 300

[ai.models."deepseek-reasoner".request]
model = "deepseek-reasoner"
thinking_type = "enabled"
frequency_penalty = 0.0
max_tokens = 32768
presence_penalty = 0.0
response_format_type = "text"
stream = false
temperature = 1.0
top_p = 1.0
tool_choice = "none"
logprobs = false
